# These are supported funding model platforms

github: [SAGS00]
# patreon: # your_patreon_username
# open_collective: # your_open_collective_username
# ko_fi: # your_ko_fi_username
# tidelift: # npm/package-name
# community_bridge: # project-name
# liberapay: # your_liberapay_username
# issuehunt: # your_issuehunt_username
# otechie: # your_otechie_username
# lfx_crowdfunding: # project-name
# polar: # your_polar_username
# buy_me_a_coffee: # your_buy_me_a_coffee_username
# thanks_dev: # your_thanks_dev_username
# custom: # Add custom sponsorship URLs (up to 4)
