name: Question
description: Ask a question about the project
title: "[QUESTION] "
labels: ["question"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to ask a question! Please fill out the form below.

    - type: textarea
      id: question
      attributes:
          label: Question
          description: What would you like to know?
          placeholder: Tell us your question
      validations:
          required: true

    - type: textarea
      id: context
      attributes:
          label: Additional Context
          description: Add any other context or screenshots about your question here.
          placeholder: Any additional information that might help us understand your question better

    - type: checkboxes
      id: checklist
      attributes:
          label: Checklist
          description: Please confirm the following
          options:
              - label: I have searched existing issues and discussions
                required: true
              - label: I have read the documentation
                required: true
